POST https://api.openai.com/v1/chat/completions
content-type: application/json
Authorization: Bearer {{key}}

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "How many ducks fit in a pond?"
    }
  ],
  "functions": [
    {
      "name": "locationQuery",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "If US: 'New York,NY,US'. else: 'london,UK'. Use ISO-3166"
          },
          "unit": {
            "type": "string",
            "description": "location unit: metric or imperial."
          }
        },
        "required": [
          "location",
          "unit"
        ]
      }
    },
    {
      "name": "authorQuery",
      "description": "Information about an author.",
      "parameters": {
        "type": "object",
        "properties": {
          "firstname": {
            "type": "string",
            "description": "First name of author."
          },
          "lastname": {
            "type": "string",
            "description": "Last name of author."
          }
        },
        "required": [
          "firstname",
          "lastname"
        ]
      }
    }
  ],
  "function_call": {"name": "authorQuery"}
}